feat: empty clipboard after 10s
for totp and passwords only

diff --git a/bwf b/bwf
--- a/bwf
+++ b/bwf
@@ -1,10 +1,9 @@
 #!/bin/zsh
-
 set -e
 
 # @description shows usage of command
-bwf_usage () {
-    cat <<EOF
+bwf_usage ()
+{    cat <<EOF
 Bitwarden using fzf
 
 Usage
@@ -23,6 +22,8 @@ if neither `-p` and `-u` are not defined, `-u` is set
 CLIPBOARD
     Uses xclip to paste username into clipboard and
     password to primary selection.
+
+    The clipboard is emptied after 10s
 
 LOGIN
     To be logged in make sure to set the environment variable
@@ -44,13 +45,13 @@ EOF
 # @description Helper function to check if a given tool is installed, otherwise die
 # @arg $1 string name of the binary
 # @arg $2 string additional text to the error message (e.g. where to download)
-need() {
-   which "$1" &>/dev/null || echo "Binary '$1' is missing but required\n$2" || exit 1
+need()
+{   which "$1" &>/dev/null || echo "Binary '$1' is missing but required\n$2" || exit 1
 }
 
 # @description Edit fzf-command to change appearance
-fzf_command () {
-   local items=$(bw get item {-1})
+fzf_command ()
+{   local items=$(bw get item {-1})
    local type=$(jq -c -e '.type' <<< "$items")
    local preview='bw get item {-1} | jq -C -r ".| {name: .name, username: .login.username, password: .login.password, notes: .notes, uri: .login.uris[] }" '
    if [ -v "$TMUX" ]; then
@@ -63,15 +64,15 @@ fzf_command () {
 }
 
 # @description gets a single items (json)
-bwf_getsingleitem () {
-   if [ -z "$allItems" ]; then
+bwf_getsingleitem ()
+{   if [ -z "$allItems" ]; then
       allItems=$(bw get item "$account")
    fi
 }
 
 # @description gets all items (json)
-bwf_getitems () {
-   if [ -z "$allItems" ]; then
+bwf_getitems ()
+{   if [ -z "$allItems" ]; then
       allItems=$(bw list items)
    fi
 }
@@ -79,8 +80,8 @@ bwf_getitems () {
 # @description gets the id of the selected item
 # * if `ACCOUNT_NAME` is provided, then return a single item
 # * if `ACCOUNT_NAME` is not provided, then ask user to select from all accounts
-bwf_getitem () {
-   if [ -z "$item" ]; then
+bwf_getitem ()
+{   if [ -z "$item" ]; then
       if [ ! -z "$account" ]; then
          bwf_getsingleitem
          item=$(jq -r '.id' -c <<< "${allItems}")
@@ -99,8 +100,8 @@ bwf_getitem () {
 }
 
 # @description grabs username for given account
-bwf_getuser () {
-   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
+bwf_getuser ()
+{   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
       item=$*
          <<< "${allItems}"
    else
@@ -111,8 +112,8 @@ bwf_getuser () {
 }
 
 # @description grabs password for given account
-bwf_getpassword () {
-   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
+bwf_getpassword ()
+{   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
       item=$*
    else
       bwf_getitem
@@ -122,8 +123,8 @@ bwf_getpassword () {
 }
 
 # @description grabs totp for given account
-bwf_gettotp () {
-   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
+bwf_gettotp ()
+{   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
       item=$*
    else
       bwf_getitem
@@ -132,14 +133,20 @@ bwf_gettotp () {
 }
 
 # @description grabs notes for given account
-bwf_getnotes () {
-   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
+bwf_getnotes ()
+{   if [ "$#" -gt 0 ] && [ -z "$1" ]; then
       item=$*
    else
       bwf_getitem
    fi
    jq -r 'map(select(.id == "'"$item"'")) | .[] | .notes' \
          <<< "${allItems}"
+}
+
+# @description empties the clipboard after 10s
+bfw_emptyclipboard()
+{   sleep 10
+   echo "" | xclip -selection clipboard -i | echo "✔ clipboard emptied"
 }
 
 xflag=0
@@ -213,6 +220,7 @@ fi
 if [ $pflag -gt 0 ]; then
    if [ $xflag -gt 0 ]; then
       bwf_getpassword "$item" | xclip -selection clipboard -i | echo "✔ password copied to clipboard"
+      bfw_emptyclipboard
    else
       bwf_getpassword "$item"
    fi
@@ -228,7 +236,8 @@ fi
 
 if [ $tflag -gt 0 ]; then
    if [ $xflag -gt 0 ]; then
-      bwf_gettotp "$item" | xclip -selection clipboard -i | echo "✔ totp copied to clipboard"
+      bwf_gettotp "$item" | xclip -selection clipboard -i | echo "✔ onetime password copied to clipboard"
+      bfw_emptyclipboard
    else
       bwf_gettotp "$item"
    fi
